In [36]:
# 별칭을 tf으로 하는 것이 일반적!

import tensorflow as tf
print(tf.__version__)

2.5.0


In [37]:
# 거의 대부분 우리가 직접 tensor(텐서)를 생성하는 경우는 없습니다.
# Tensorflowrk가 tr.io나 tf.data라는 모듈을 기본적으로 가지고 있어서,
# 데이터를 가져와서 자동으로 tensor로 전환 (변환)을 해줍니다.
# 이 변환된 텐서를 나중에 neural network(신경망)에서 사용합니다.

# tensor를 이해하기 위해 직접 만들어 보겠습니다.
# tensorflow에서 사용하는 (constant)를 생성
# scalar를 생성 (rank가 0인 텐서), scalar는 어떠한 차원을 가지고 있지 않기 때0문! 그냥 단순히 숫자!
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [38]:
# 해당 텐서의 차원 수를 알려줍니다. ndim은 number of dimensions의 약자 해당 텐서의 차원 수를 알려줍니다.
scalar.ndim

0

In [39]:
# 벡터를 생성 (차원이 0보다 큰 것)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [40]:
vector.ndim

1

In [41]:
# 행렬 (matrix)생성 (차원이 1보다 큰것)
matrix = tf.constant([
    [10, 7],
    [7, 10]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [42]:
matrix.ndim

2

In [43]:
# Tensorflow는 기본적으로 int32나 float32 자료형으로 tensor를 생성합니다.
# 32-bit precision이다! 숫자가 높으면 높을 수록 precision도 높아지고 컴퓨터가 사용할 메모리 커집니다.

In [44]:
# 새로운 행렬을 생성하고 데이터형을 지정
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [45]:
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [46]:
another_matrix.ndim

2

In [47]:
# tensor를 생성 (차원이 2보다 큰것)
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [48]:
tensor.ndim

3

In [49]:
# rank = dimension
# scalar, vector, matrix, tensor로 굳이 앞에서 정의를 했지만,
# 이론적으로 모두 tensor 입니다. 즉 rank가 0, 1, 2, 3인 tensor로 이야기 할 수 있습니다.
# tensor는 임의 (즉,  제한이 없는) 차원을 가질수 있습니다.

In [50]:
# 이미지들을 처리한다고 할 때, (224, 224, 3, 32)라고 표현을 할 떄
# 224, 224는 픽셀로 표현을 했을때 높이와 너비를 의미하고,
# 3은 이미지 채널 수 (red, greed, blue)
# 32는 배치 사이즈 (1번 실행시 신경망이 1번에 처리할 수 있는 이미지의 갯수)

In [51]:
# 위에서 선언한 모든 constant는 모두 tensor에 속하지만, 위에서와 각자의 부른 이름 존재
# scalar: 단일한 숫자 (0차원 tensor)
# vector: 방향이 있는 숫자 (1차원 tensor)
# matrix: 숫자로 이루어진 2차원 배열 (2차원 tensor)
# tensor: 숫자로 이루어진 n차원 배열

![스칼라 벡터 행렬 텐서 구분하기](scalar-vector-matrix-tensor.png)

In [54]:
# 변수 생성
# tf.Variable()

In [55]:
# tf.Variabel와 tf.constant의 차이점
# ==> tf.constant로 생성한 텐서는 immutable (변경 불가)
# ==> tf.Variable로 생성한 텐서는 mutable (변경 가능)

In [ ]:
changeable_tensor = tf.Variable([10, 7])

In [57]:
unchangeable_tensor = tf.constant([10, 7])

In [58]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [59]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [60]:
# tf.constant 및 tf.Variable중에 어떤 것을 사용해야 할까요?
# 상황에 따라 다릅니다. Tensorflow가 우리를 위해서 tensor를 직접 생성하는데,
# 이때(데이터를 불러올 때나 데이터를 모델링) 알아서 constant 및 Variable를 선택해서 생성합니다.

In [61]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [62]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

[psedurandom numper]https://www.computerhope.com/jargon/p/pseudo-random.htm

[tensorflow random number API를 설명한 웹페이지]https://www.tensorflow.org/guide/random_numbers?hl=ko

In [65]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

In [66]:
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [68]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [69]:
not_shuffled.ndim

2

In [94]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [103]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

[set seed 설명 웹페이지] https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [104]:
# tf.random.set_seed(42)

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [105]:
tf.ones(shape=(3, 2, 3))

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [106]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

# 1
## 2
### 3
#### 4
##### 5
###### 6

## tensor의 형태와 numpy array의 형식이 같다
### tensor는 GPU에서 실행이 가능하다

### 행렬이나 텐서는 대문자로 이름 표기하고
### 벡터는 소문자로 이름을 표기

In [122]:
import numpy as np

numpy_A = np.arange(1, 26, dtype=np.int32) # 1 ~ 25를 포함하는 Numpy array을 생성
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int32)

In [123]:
tensor_A = tf.constant(numpy_A, shape = [1, 5, 5]) # 5행 5열 짜리 행렬을 1개가 존재하는 텐서를 생성
tensor_A

<tf.Tensor: shape=(1, 5, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]], dtype=int32)>

In [124]:
tensor_A.ndim

3

# tensor (텐서)에서 정보를 얻어오기 

* Shape : 텐서의 차원에 존재하는 값들의 개수
* Rank : 텐서 차원의 수, Scalar는 rank 0, Vector는 rank 1, Matrix는 rank 2, tensor rank가 n
* Axis : Rank와 같다
* Dimension : Rank와 같다
* Size : tensor에 존재하는 값을 총 개수

In [127]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [128]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [129]:
print("텐서에 존재하는 값들의 자료형 : ", rank_4_tensor.dtype)
print("텐서에 차원 (rank) : ", rank_4_tensor.ndim)
print("텐서에 0번째 axis : ", rank_4_tensor.shape[0])
print("텐서에 마지막 axis : ", rank_4_tensor.shape[-1])
print("텐서에 모든 값들의 갯수 : ", tf.size(rank_4_tensor).numpy())

텐서에 존재하는 값들의 자료형 :  <dtype: 'float32'>
텐서에 차원 (rank) :  4
텐서에 0번째 axis :  2
텐서에 마지막 axis :  5
텐서에 모든 값들의 갯수 :  120


In [130]:
# Numpy array -> tensor 변환 가능
# tensor -> Numpy array 변환 가능

In [132]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [133]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>