In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [3]:
# 각 행의 마지막 열의 값을 가져오기
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [4]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

# 파이썬에서는 ... 은 모든 것을 의미합니다. rank2_tensor에 존재하는 모든 것

In [5]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [6]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [7]:
rank_3_tensor = rank_2_tensor[tf.newaxis, ...]

In [8]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4]]], dtype=int32)>)

In [9]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [10]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1의 의미는 파이썬는 마지막이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [11]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [12]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [13]:
# tensor 가지고 놀아보기!
# 사칙연산 + - *

[Tensorflow의 math API](https://www.tensorflow.org/api_docs/python/tf/math/)

In [14]:
tensor = tf.constant([
    [10, 7], 
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [15]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [16]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [17]:
tensor_plus_10 = tensor + 10
tensor_plus_10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [18]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [19]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [20]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [21]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [22]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [23]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [24]:
tf.divide(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [25]:
# 머신 러닝 알고리즘에서 가장 많이 사용하는 연산 중에 하나 행렬 연산 (Matrix multiplication)
# Tensorflow에서는 tf.matmul() 메소드로 matrix multiplication을 구현해 놓았습니다.

[참고](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [26]:
# matrix multiplication를 실행할 때 꼭 기억해야 할 것 2개가 있습니다.

1. 각 행렬을 multiplication을 할 때 안에 있는 차원은 같아야 한다.

   (3, 5) @ (3, 5) : 행렬 연산이 안 됨

   (5, 3) @ (3, 5) : 행렬 연산이 가능

   (3, 5) @ (5, 3) : 행렬 연산이 가능

2. 행렬 연산의 결과의 행렬의 크기는 바깥의 차원와 같다.

   (5, 3) @ (3, 5) -> (5, 5)
   
   (3, 5) @ (5, 3) -> (3, 3)

@ : 파이썬에서 matrix multiplication을 의미

In [27]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [28]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [29]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [30]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [31]:
X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [32]:
# X, Y는 현재 shape가 (3, 2)!
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [33]:
# 위의 경우에 matrix multiplication을 하려면
# 1. X의 shape를 (2, 3)로 바꾸는 경우   (2, 3) @ (3, 2)
# 2. Y의 shape를 (2, 3)로 바꾸는 경우   (3, 2) @ (2, 3)

In [34]:
# tf.reshape() : 텐서의 shape를 우리가 정의한 shape로 변경해 주는 메서드
# tf.transpose() : 주어진 행렬의 행과 열을 바꾸어 주는 메서드

In [35]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [36]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [37]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [38]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [39]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [40]:
tf.matmul(a=X, b=Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [41]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [42]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [43]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [44]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [45]:
Y, tf.reshape(Y, (2, 3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [46]:
# 16-비트 floating precision vs. 32-비트 floating precision
# 낮은 precision이 모바일 장치와 같은 컴퓨팅이나 메모리가 작을 경우에 유용

In [47]:
B = tf.constant([
    [1.7, 7.4]
])

C = tf.constant([
    [1, 7]
])

B, C

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.7, 7.4]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 7]], dtype=int32)>)

In [48]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.7, 7.4]], dtype=float16)>

In [49]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 7.]], dtype=float32)>

In [50]:
# 절대값 구하기
D = tf.constant([
    [-7, -10]
])
D

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ -7, -10]], dtype=int32)>

In [51]:
tf.abs(D)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 10]], dtype=int32)>

In [52]:
# aggregation 함수 사용하기 min, max, mean, sum)
# tf.reduce_min()
# tf.reduce_max()
# tf.reduce_mean()
# tf.reduce_sum()


In [53]:
np.random.randint(low = 0, high = 100, size =50)

array([94, 91, 92, 40, 13, 42, 97, 50, 50, 21, 45, 96, 52,  8, 81, 34, 44,
       33, 58, 89, 93, 37, 95, 12, 13, 90, 65, 56, 54, 82, 32, 33, 30, 81,
       99, 94, 89, 35, 30, 41, 22,  6,  0, 23, 83, 12, 26, 45, 68, 64])

In [54]:
type(np.random.randint(low = 0, high = 100, size =50))

numpy.ndarray

In [55]:

E = tf.constant(np.random.randint(low = 0, high = 100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 72, 72, 62, 38, 67, 93, 99, 62, 43, 16, 96, 26, 62, 58, 41, 38,
       16, 83, 99,  9, 64,  3, 94, 37, 34, 68, 83, 63,  4, 37, 49, 60, 66,
       97, 31, 32, 50, 87,  0, 81, 17, 89, 68, 32, 84, 41, 93, 14, 54])>

In [56]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [57]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [58]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [59]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2723>

In [60]:
F = tf.constant(np.random.random(50)) # 0 ~ 1사이의 값을 랜덤으로 만들어 준다.
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([9.01523305e-01, 9.96818986e-01, 7.03406067e-01, 5.91773925e-01,
       5.74444736e-01, 2.87005203e-01, 7.89446406e-01, 7.82634456e-01,
       3.84567351e-01, 3.59596115e-01, 8.32841431e-01, 5.82285691e-01,
       1.90907506e-01, 7.49376510e-01, 9.26238667e-01, 2.35969276e-01,
       4.02873050e-01, 3.72470968e-01, 2.50214764e-01, 8.54113560e-01,
       2.08301348e-01, 6.40049126e-01, 2.07853826e-01, 6.21254224e-01,
       1.69569315e-01, 9.12583840e-01, 8.58710168e-01, 2.55932139e-01,
       2.10932839e-01, 3.83470303e-01, 6.45160096e-01, 2.72979448e-02,
       2.79904570e-01, 7.10515836e-01, 6.08593272e-01, 5.30662948e-01,
       8.50780504e-02, 9.77854351e-01, 6.03348006e-01, 3.70170210e-01,
       4.80441941e-01, 5.00857969e-01, 5.43883165e-01, 2.93976979e-01,
       8.66072082e-02, 6.72838813e-01, 2.42314376e-01, 7.45649952e-04,
       9.70794600e-01, 9.19110252e-02])>

In [61]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [62]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [63]:
print("F에서의 최대값의 위치 : ", tf.argmax(F).numpy())
print("F에서의 최대값 :", tf.reduce_max(F).numpy())
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 : ", F[tf.argmax(F)].numpy())
print("F에서의 최소값의 위치 : ", tf.argmin(F).numpy())
print("F에서의 최소값 :", tf.reduce_min(F).numpy() )
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값은 같을까요? ", F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy())

F에서의 최대값의 위치 :  1
F에서의 최대값 : 0.9968189862135121
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 :  0.9968189862135121
F에서의 최소값의 위치 :  47
F에서의 최소값 : 0.0007456499518281312
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값은 같을까요?  True


In [64]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 2, 25))
G.shape, G.ndim, G

(TensorShape([1, 1, 1, 2, 25]),
 5,
 <tf.Tensor: shape=(1, 1, 1, 2, 25), dtype=int64, numpy=
 array([[[[[62, 74, 59, 23, 58, 70, 71, 33, 99, 51, 58, 64, 45,  6,  9,
            38, 43, 60, 40, 32, 54, 76, 16, 37, 78],
           [18, 83, 78, 37, 97, 49, 91, 49, 10, 43, 42, 59, 40, 85, 64,
             4, 66, 49, 93, 80,  9, 85, 73, 22, 76]]]]])>)

In [65]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim, G_squeezed

(TensorShape([2, 25]),
 2,
 <tf.Tensor: shape=(2, 25), dtype=int64, numpy=
 array([[62, 74, 59, 23, 58, 70, 71, 33, 99, 51, 58, 64, 45,  6,  9, 38,
         43, 60, 40, 32, 54, 76, 16, 37, 78],
        [18, 83, 78, 37, 97, 49, 91, 49, 10, 43, 42, 59, 40, 85, 64,  4,
         66, 49, 93, 80,  9, 85, 73, 22, 76]])>)

In [66]:
# one-hot encoding
list_example = [0, 1, 2, 3]

tf.one_hot(list_example, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [67]:
tf.one_hot(list_example, depth=4, on_value="On", off_value="Off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>